[project]
name = "train-checker-bot"
version = "0.1.0"
description = "Telegram bot for checking train availability in Uzbekistan"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "aiogram>=3.15.0",
    "python-dotenv>=1.0.0",
    "aiosqlite>=0.20.0",
]
